{{- range $sec := .Values.secrets | default list }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sec.name }}
  namespace: {{ $sec.namespace }}
{{- if $sec.annotations }}
  annotations:
{{ $sec.annotations | toYaml | indent 4 }}
{{- end }}
  labels:
{{ include "flux-loop.labels" $ | indent 4 }}
{{- if $sec.labels }}
{{ $sec.labels | toYaml | indent 4 }}
{{- end }}
{{- if $sec.type | default "" }}
type: {{ $sec.type }}
{{- else }}
type: Opaque
{{- end }}
data:
{{- range $key, $value := $sec.values | default dict }}
{{ $key | indent 2 }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
